import type { Metadata } from "next";
import Header from "@/components/header/Header";
import Footer from "@/components/Footer";
import { Inter } from 'next/font/google';
import './globals.css'; 
import ApolloWrapper from "@/components/ApolloWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
});

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <ApolloWrapper>
          <Header/>
            {children}
          <Footer/>
        </ApolloWrapper>
      </body>
    </html>
  );
}

export default RootLayout